Starting at: 2022-10-11 23:07:34.795830
Preprocessing time: 0.00470280647277832
k_range [1, 3]
k:  1
k:  2
530
k:  3
530
530
calculating results for fold None
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 199, in get_01_loss_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 284, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 84, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 118, in find_k_nearest_neighbors
    for i in range(len(self.training_data.index)):
TypeError: object of type 'builtin_function_or_method' has no len()
calculating results for fold None
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 199, in get_01_loss_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 284, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 84, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 118, in find_k_nearest_neighbors
    for i in range(len(self.training_data.index)):
TypeError: object of type 'builtin_function_or_method' has no len()
calculating results for fold None
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 199, in get_01_loss_for_k
    fold_results = cv.calculate_results_for_fold(algorithm, test_data, predict_params=[k])
  File "/home/braeden/Git/csci447-project-01/Project02/source/Evaluation/CrossValidation.py", line 284, in calculate_results_for_fold
    prediction = algorithm.predict(sample, *predict_params)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 84, in predict
    neighbors_distance = self.find_k_nearest_neighbors(instance, k)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Algorithms/KNN.py", line 118, in find_k_nearest_neighbors
    for i in range(len(self.training_data.index)):
TypeError: object of type 'builtin_function_or_method' has no len()
{}
Traceback (most recent call last):
  File "/home/braeden/Git/csci447-project-01/Project02/main.py", line 601, in <module>
    run_breast_cancer_experiment(False, False, True)
  File "/home/braeden/Git/csci447-project-01/Project02/main.py", line 334, in run_breast_cancer_experiment
    all_params_kmeans = tuning_utility_kmeans.tune_k_for_folds(training_test_data, tuning_data, k_range=[1,3], clusters=clusters)
  File "/home/braeden/Git/csci447-project-01/Project02/source/Utilities/TuningUtility.py", line 104, in tune_k_for_folds
    results_df.columns = ['k', '0/1', 'Model']
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 5588, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 769, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 214, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/base.py", line 69, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements
